package main

import "fmt"

func runHelp() {
	fmt.Print(banner)
	fmt.Println("Usage: vox [command]")
	fmt.Println()
	fmt.Println("Commands:")
	fmt.Println("  (none)     Start dictation (default)")
	fmt.Println("  setup      Check permissions, install deps, configure features")
	fmt.Println("  help       Show this help message")
	fmt.Println("  version    Show version")
	fmt.Println()
	fmt.Println("Environment Variables:")
	fmt.Println("  VOX_HOTKEY          Hotkey (default: option+space)")
	fmt.Println("  VOX_HOLD_TO_TALK    Hold-to-talk mode (default: true)")
	fmt.Println("  VOX_LANGUAGE        Language code (default: auto-detect)")
	fmt.Println("  VOX_VERBOSE         Debug logging (default: false)")
	fmt.Println("  WHISPER_URL         Whisper server URL (default: http://127.0.0.1:2022)")
	fmt.Println("  VOX_VOCAB_TERMS     Comma-separated custom terms for whisper")
	fmt.Println("  VOX_VOCAB_FILE      Path to vocab file (one term per line)")
	fmt.Println("  ANTHROPIC_API_KEY   Claude API key (enables AI features)")
	fmt.Println("  VOX_LD_SDK_KEY      LaunchDarkly SDK key (enables flag control)")
	fmt.Println()
	fmt.Println("AI Features (require ANTHROPIC_API_KEY):")
	fmt.Println("  VOX_AI_POSTPROCESS  Clean up grammar/punctuation via Claude")
	fmt.Println("  VOX_PROMPT_MODE     Voice shortcuts: \"summarize my clipboard\"")
	fmt.Println("  VOX_VOICE_COMMANDS  Voice commands: \"create PR\", \"query flag\"")
	fmt.Println("  VOX_CONTEXT_AWARE   Format output based on focused app")
	fmt.Println("  VOX_AI_MODEL        Claude model (default: claude-haiku-4-5-20251001)")
	fmt.Println()
	fmt.Println("Quick Start:")
	fmt.Println("  1. make setup           # install deps + check permissions")
	fmt.Println("  2. make start           # start whisper + vox")
	fmt.Println("  3. Hold Option+Space    # speak, release to paste")
	fmt.Println()
	fmt.Println("Docs: https://github.com/mattthewong/vox")
}
